// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CommitmentFormController from "./commitment_form_controller"
application.register("commitment-form", CommitmentFormController)

import CommitmentScheduleController from "./commitment_schedule_controller"
application.register("commitment-schedule", CommitmentScheduleController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MarkdownEditorController from "./markdown_editor_controller"
application.register("markdown-editor", MarkdownEditorController)

import MobileAsideController from "./mobile_aside_controller"
application.register("mobile-aside", MobileAsideController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PosturacorrettastartController from "./posturacorrettastart_controller"
application.register("posturacorrettastart", PosturacorrettastartController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import TocController from "./toc_controller"
application.register("toc", TocController)

import TreeController from "./tree_controller"
application.register("tree", TreeController)
