default: &default
  flowpulse.net:
    action: mvp_home
    locale: it
    primary: true

  www.flowpulse.net:
    canonical_host: flowpulse.net

  posturacorretta.org:
    action: posturacorretta
    locale: it
    primary: true

  www.posturacorretta.org:
    canonical_host: posturacorretta.org

  markpostura.it:
    action: markpostura
    locale: it
    primary: true
  
  www.markpostura.it:
    canonical_host: markpostura.it

  markpostura.com:
    action: markpostura
    locale: it
    primary: true
  
  www.markpostura.com:
    canonical_host: markpostura.com


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
