service: flowpulse_v_5
image: marcobeffa/flowpulse_v_5

servers:
  web:
    - 178.105.106.247

registry:
  server: ghcr.io
  username: marcobeffa
  password:
    - KAMAL_REGISTRY_PASSWORD

proxy:
  ssl: true
  host: flowpulse.net

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_TO_STDOUT: true
    DB_HOST: flowpulse_v_5-db
    DB_PORT: 5432
    DB_NAME: flowpulse_v_5_production
    DB_USERNAME: flowpulse

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "flowpulse_v_5_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:16
    host: 178.105.106.247
    env:
      clear:
        POSTGRES_DB: flowpulse_v_5_production
        POSTGRES_USER: flowpulse
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
