service: flowpulse_v_5
image: marcobeffa/flowpulse_v_5
deploy_timeout: 180

servers:
  web:
    - 178.105.106.247

registry:
  server: ghcr.io
  username: marcobeffa
  password:
    - KAMAL_REGISTRY_PASSWORD

proxy:
  ssl: true
  hosts:
    - flowpulse.net
    - www.flowpulse.net
    - posturacorretta.org
    - www.posturacorretta.org
    - markpostura.it
    - www.markpostura.it
    - markpostura.com
    - www.markpostura.com
    
  healthcheck:
    path: /up
    interval: 3
    timeout: 5

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: false
    RUN_DB_PREPARE_ON_BOOT: false
    RAILS_LOG_TO_STDOUT: true
    DB_HOST: flowpulse_v_5-db
    DB_PORT: 5432
    DB_NAME: flowpulse_v_5_production
    DB_USERNAME: flowpulse
    APP_HOSTS: "flowpulse.net,www.flowpulse.net,posturacorretta.org,www.posturacorretta.org,markpostura.it,www.markpostura.it,markpostura.com,www.markpostura.com"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "flowpulse_v_5_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:16
    host: 178.105.106.247
    env:
      clear:
        POSTGRES_DB: flowpulse_v_5_production
        POSTGRES_USER: flowpulse
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
